# Site settings
title: Sourbh Bhadane
email: sourbh.bhadane@ee.iitm.ac.in
description: > # this means to ignore newlines until "baseurl:"
  I'm a final year BTech and MTech student in the Electrical Engineering department at IIT Madras.  
# baseurl: "/" # the subpath of your site, e.g. /blog/

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima